### ISSUE TITLE
(AWS): Discover serverless workloads

### ISSUE THREAD

**Issue by grpengue** [CrowdStrike/cloud-resource-estimator#39]
Hi guys,
Congratulations for this project, help the field a lot!
It would be great to include the list of serverless containers as well:
- Fargate Tasks
- ACI
- Google Run

**Comment by gadouryd** [comment]
Anything we can do to prioritize this would be incredibly helpful to the field. The number of customers using serverless is continuing to increase. Please update to also include support for GKE Autopilot.

**Comment by yannhowe** [comment]
+1

**Comment by carlosmmatos** [comment]
I might split this up into 3 separate issues - one for each cloud provider

**Comment by carlosmmatos** [comment]
AWS: #39
GCP: #41 
Azure: #42

**Comment by carlosmmatos** [comment]
@gadouryd | @yannhowe | @grpengue can we get your input for PR #43
